# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage:
  jobs:
  - job:
    steps:
    - script: pwd
      displayName: 'Mostrar en donde estoy cuando ejecuto el pipeline'

    - script: ls
      displayName: 'Mostrar archivos en la maquina'
